export const SET_CLIENT_DIMENSIONS: any = "SET_CLIENT_DIMENSIONS";
export const REGISTER_USER: any = "REGISTER_USER";
export const REGISTER_USER_SUCCESS: any = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE: any = "REGISTER_USER_FAILURE";
